### PR TITLE
Move docs out to docs task that pushes to gh-pages branch - wip

### PR DESCRIPTION
**Pull request by cliftonc**
As per #86.

Running gulp docs pushes to gh-pages - so it WILL push and update whatever is there if you have push access to the main FGRibreau/doxx repo (can have this dry run if necessary).

```
gulp docs
```

Docs no longer generated on build.  

There is an index file (empty atm) in docs that should contain the new doxx home page, and will be fairly static.  It cleans up after itself so the only things we see in the commit / PR history will be changes to actual code.

### CODE REVIEW

**Comment by cliftonc** [comment]
Updated to remove the push - you need to push the gh-pages branch yourself, safer.

**Comment by FGRibreau** [comment]
Nice!

**Comment by FGRibreau** [comment]
@iwatakeshi is that OK with you too?

**Comment by iwatakeshi** [comment]
@cliftonc @FGRibreau You guys rock. :+1:  Let's do it!

**Comment by cliftonc** [comment]
:) I hadn't gotten around to a nice index page - so we should hold off on publishing the docs!  I was thinking something bootstrap / simple that linked off to the cayman + default versions?

**Comment by iwatakeshi** [comment]
@cliftonc My apologies, I understood as if it was completed. No worries, @FGRibreau won't publish it yet, but yes, simple would be nice.

**Pull request merged**
