### PR TITLE
Update Doxx

### LINKED ISSUE #70: Using @description tag doubles the description
It seems like for a comment like:
```javascript
   /** 
   * @public
   * @description Parses the headers for the Accept-Language.
   * @param  {object} req The request object.
   * @return {string|undefined}     The parsed Accept-Language.
   */
```
outputs in the html as:

```
Parses the headers for the Accept-Language.
Parses the headers for the Accept-Language.
```
The position of the `@description` tag does not seem to matter, it will always double the description.

Side-note: I'm currently using the gulp-doxx plugin.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26312907-using-description-tag-doubles-the-description?utm_campaign=plugin&utm_content=tracker%2F332585&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F332585&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by iwatakeshi**
As far as version number, I'm not sure what this update would be considered, but the following changes have been made:

-  [x] The `lib` is now written in ES6 and should be developed there and not in `src`
-  [x] Temporarily fix #70 
-  [x] Updated `commander.js` so that the options are shorter. i.e. `target_extension` is just `extension` and `-j` represents `--template`
-  [x] Replaced grunt with gulp and made the build process much easier to understand
-  [x] Updated Prism.js to support ES6 syntax
-  [x] Updated template to support basic ES6 syntax... just the `extends` part.
-  [x] Updated tests by switching to mocha as it makes the test process easier with gulp.
-  [x] Updated REAMDE
-  [x] Fixed License extension

### CODE REVIEW

**Comment by FGRibreau** [comment]
> Updated commander.js so that the options are shorter. i.e. target_extension is just extension and -j represents --template

At least this statement will make it a major version :)

**Comment by iwatakeshi** [comment]
:+1:

**Comment by FGRibreau** [comment]
@iwatakeshi released in v2.0.0! \o/

**Comment by iwatakeshi** [comment]
@FGRibreau :+1: I'm glad I was able to help! :)

**Pull request merged**
